global:
  scrape_interval:     5s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s)

scrape_configs:
  - job_name: 'App localhost'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8080']  # host.docker.internal вместо 'localhost:8080' т.к. используется bridge network
        labels:
          application: 'App localhost'
  - job_name: 'App docker'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['dev-service:8080']  # by name of container in bridge network
        labels:
          application: 'App docker'