apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    label: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090 # by container name
    isDefault: true
    uid: PrometheusUid  # replace in <dash>.json - "datasource": "${DS_PROMETHEUS}"
